development:
  adapter: mysql
  database: filo_development
  username: matteo
  password:
  host: localhost

test:
  adapter: mysql
  database: filo_test
  username: matteo
  password:
  host: localhost

production:
  adapter: mysql
  database: filo_production
  username: root
  password: 
  host: localhost
