development:
  adapter: mysql
  database: filo_development
  username: matteo
  password:
  host: localhost

test:
  adapter: mysql
  database: filo_test
  username: matteo
  password:
  host: localhost

production:
  adapter: mysql
  database: mvaccari_db1
  username: mvaccari1
  password: questa-e-difficilissima-da-indovinare-percio-l-ho-scelta
  host: localhost
