development:
  adapter: mysql
  database: filo_development
  username: filo
  password: filo
  host: localhost

test:
  adapter: mysql
  database: filo_test
  username: filo
  password: filo
  host: localhost

production:
  adapter: mysql
  database: filo_production
  username: filo
  password: du2choo0meuF9eey
  host: localhost
